name: CI

on: [push]

jobs:
  phytest:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v2
      with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: nextstrain
          use-mamba: true
    - name: Cache Conda env
      uses: actions/cache@v2
      with:
        path: ${{ env.CONDA }}/envs
        key: conda-${{ runner.os }}--${{ runner.arch }}-${{ hashFiles('env.yaml') }}-${{ env.CACHE_NUMBER }}
      env:
        # Increase this value to reset cache if env.yaml has not changed
        CACHE_NUMBER: 0
      id: cache
    - name: Update environment
      run: mamba env update -n nextstrain -f env.yaml
      if: steps.cache.outputs.cache-hit != 'true'
    - name: Run snakemake
      run: |
        snakemake -c 1
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: report # The branch the action should deploy to.
        folder: results/phytest # The folder the action should deploy.
