name: CI

on: [push]

jobs:
  phytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: Cache conda
      uses: actions/cache@v2
      env:
        # Increase this value to reset cache if env.yaml has not changed
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
          hashFiles('env.yaml') }}
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: anaconda-client-env
        channel-priority: strict
        environment-file: env.yaml
        use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
    - name: Run snakemake
      run: |
        snakemake -c 1
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: report # The branch the action should deploy to.
        folder: results/phytest # The folder the action should deploy.
