name: CI

on: [push]

jobs:
  phytest:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.6
        mamba-version: "*"
        channels: conda-forge,defaults
        channel-priority: true
        activate-environment: nextstrain
        environment-file: env.yaml
    - shell: bash -l {0}
      run: |
        conda info
        conda list
        conda config --show-sources
        conda config --show
        printenv | sort
    - name: Run snakemake
      run: |
        snakemake -c 1
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: report # The branch the action should deploy to.
        folder: results/phytest # The folder the action should deploy.
