name: CI

on: [push]

jobs:
  phytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        conda env create -n nextstrain --file env.yaml
        conda activate nextstrain
    - name: Run phytest
      run: |
        snakemake -c 1
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: report # The branch the action should deploy to.
        folder: results/phytest # The folder the action should deploy.
